import type { RoleConfig, Round } from '../types/game';

// Cấu hình cho từng vai trò
export const ROLES: Record<string, RoleConfig> = {
  smallbiz: {
    id: 'smallbiz',
    name: 'Small Business',
    description: 'Doanh nghiệp nhỏ - Cạnh tranh với nền tảng lớn',
    icon: '🏪',
    primaryMetrics: ['revenue', 'marketShare', 'innovation'],
    initialMetrics: {
      revenue: 50,
      marketShare: 30,
      userTrust: 60,
      innovation: 70,
      publicWelfare: 50,
      fairness: 50,
    },
  },
  platform: {
    id: 'platform',
    name: 'Big Tech Platform',
    description: 'Nền tảng công nghệ lớn - Cân bằng lợi nhuận và trách nhiệm',
    icon: '🏢',
    primaryMetrics: ['revenue', 'marketShare', 'userTrust'],
    initialMetrics: {
      revenue: 80,
      marketShare: 70,
      userTrust: 50,
      innovation: 60,
      publicWelfare: 40,
      fairness: 45,
    },
  },
  regulator: {
    id: 'regulator',
    name: 'Regulator',
    description: 'Cơ quan quản lý - Đảm bảo cạnh tranh công bằng',
    icon: '⚖️',
    primaryMetrics: ['publicWelfare', 'fairness'],
    initialMetrics: {
      revenue: 0,
      marketShare: 0,
      userTrust: 60,
      innovation: 50,
      publicWelfare: 70,
      fairness: 70,
    },
  },
};

// Số vòng chơi
export const TOTAL_ROUNDS = 5;

// Kịch bản và lựa chọn cho từng vai trò
export const SMALLBIZ_ROUNDS: Round[] = [
  {
    roundNumber: 1,
    scenario: 'Nền tảng lớn bắt đầu áp dụng chính sách ưu tiên sản phẩm của họ trong kết quả tìm kiếm. Doanh số của bạn giảm 30%. Bạn sẽ làm gì?',
    choices: [
      {
        id: 'sb1_a',
        title: 'Khiếu nại lên cơ quan quản lý',
        description: 'Tố cáo hành vi cạnh tranh không lành mạnh',
        effects: { fairness: 10, revenue: -5, marketShare: -5 },
        riskLevel: 'low',
        consequence: 'Quá trình pháp lý mất thời gian, doanh thu ngắn hạn giảm',
        tags: ['ethical', 'defensive'],
      },
      {
        id: 'sb1_b',
        title: 'Tăng chi phí quảng cáo trên nền tảng',
        description: 'Chi nhiều tiền hơn để xuất hiện trên top',
        effects: { revenue: -15, marketShare: 10, innovation: -5 },
        riskLevel: 'medium',
        consequence: 'Chi phí tăng cao, lợi nhuận giảm',
        tags: ['aggressive'],
      },
      {
        id: 'sb1_c',
        title: 'Đổi mới sản phẩm để tạo khác biệt',
        description: 'Tập trung vào tính năng độc đáo',
        effects: { innovation: 15, revenue: 5, userTrust: 10, marketShare: 5 },
        riskLevel: 'medium',
        consequence: 'Cần thời gian để khách hàng nhận biết',
        tags: ['innovation'],
      },
      {
        id: 'sb1_d',
        title: 'Xây dựng cộng đồng khách hàng trung thành',
        description: 'Tạo chương trình khách hàng thân thiết và tương tác trực tiếp',
        effects: { userTrust: 20, revenue: 8, marketShare: 5, innovation: 5 },
        riskLevel: 'low',
        consequence: 'Giảm phụ thuộc vào nền tảng, tăng sự gắn kết',
        tags: ['defensive', 'balanced'],
      },
    ],
  },
  {
    roundNumber: 2,
    scenario: 'Nền tảng công bố chính sách thu phí cao hơn 20% cho sellers. Bạn có nhiều đơn hàng nhưng lợi nhuận bị ép. Quyết định của bạn?',
    choices: [
      {
        id: 'sb2_a',
        title: 'Chấp nhận và tăng giá bán',
        description: 'Chuyển gánh nặng chi phí sang khách hàng',
        effects: { revenue: -10, marketShare: -15, userTrust: -10 },
        riskLevel: 'high',
        consequence: 'Khách hàng có thể rời bỏ do giá cao',
        tags: ['aggressive'],
      },
      {
        id: 'sb2_b',
        title: 'Chuyển sang nền tảng khác',
        description: 'Thử bán hàng trên marketplace nhỏ hơn',
        effects: { revenue: -20, marketShare: -10, innovation: 10 },
        riskLevel: 'high',
        consequence: 'Mất khách hàng hiện tại, phải xây dựng lại',
        tags: ['innovation'],
      },
      {
        id: 'sb2_c',
        title: 'Xây dựng website riêng',
        description: 'Đầu tư vào kênh bán hàng trực tiếp',
        effects: { revenue: -15, innovation: 20, marketShare: 5, userTrust: 15 },
        riskLevel: 'medium',
        consequence: 'Chi phí ban đầu cao, hiệu quả dài hạn',
        tags: ['innovation', 'defensive'],
      },
      {
        id: 'sb2_d',
        title: 'Đàm phán với nền tảng',
        description: 'Tổ chức nhóm sellers để thương lượng mức phí',
        effects: { fairness: 15, revenue: 5, marketShare: 8, publicWelfare: 10 },
        riskLevel: 'medium',
        consequence: 'Cần sự đoàn kết, nhưng có thể đạt thỏa thuận tốt hơn',
        tags: ['ethical', 'balanced'],
      },
    ],
  },
  {
    roundNumber: 3,
    scenario: 'Nền tảng ra mắt sản phẩm cạnh tranh trực tiếp với bạn, sử dụng dữ liệu bán hàng của bạn để tối ưu hóa. Thị phần giảm 40%. Hành động?',
    choices: [
      {
        id: 'sb3_a',
        title: 'Kiện tụng về vi phạm dữ liệu',
        description: 'Khởi kiện nền tảng sử dụng dữ liệu trái phép',
        effects: { fairness: 15, revenue: -10, marketShare: -10 },
        riskLevel: 'high',
        consequence: 'Chi phí pháp lý cao, kết quả không chắc chắn',
        tags: ['ethical', 'aggressive'],
      },
      {
        id: 'sb3_b',
        title: 'Hợp tác với doanh nghiệp nhỏ khác',
        description: 'Liên minh để tăng sức mạnh đàm phán',
        effects: { marketShare: 15, fairness: 10, revenue: 5, innovation: 10 },
        riskLevel: 'medium',
        consequence: 'Chia sẻ lợi nhuận nhưng tăng sức ảnh hưởng',
        tags: ['balanced', 'defensive'],
      },
      {
        id: 'sb3_c',
        title: 'Pivot sang thị trường ngách',
        description: 'Tập trung vào phân khúc khách hàng đặc biệt',
        effects: { innovation: 20, userTrust: 15, revenue: 10, marketShare: -5 },
        riskLevel: 'medium',
        consequence: 'Thị trường nhỏ hơn nhưng lợi nhuận cao',
        tags: ['innovation'],
      },
      {
        id: 'sb3_d',
        title: 'Cạnh tranh trực tiếp bằng giá thấp',
        description: 'Giảm giá mạnh để giành lại khách hàng',
        effects: { marketShare: 20, revenue: -15, userTrust: -5, innovation: -10 },
        riskLevel: 'high',
        consequence: 'Cuộc chiến giá, tổn thất lợi nhuận',
        tags: ['aggressive'],
      },
    ],
  },
  {
    roundNumber: 4,
    scenario: 'Cơ quan quản lý đề xuất luật mới hạn chế hành vi độc quyền của nền tảng. Bạn được mời tham gia điều trần. Lựa chọn của bạn?',
    choices: [
      {
        id: 'sb4_a',
        title: 'Tham gia điều trần tích cực',
        description: 'Chia sẻ bằng chứng và đề xuất giải pháp',
        effects: { fairness: 20, publicWelfare: 15, marketShare: 10, revenue: 5 },
        riskLevel: 'low',
        consequence: 'Hỗ trợ tạo môi trường cạnh tranh công bằng',
        tags: ['ethical'],
      },
      {
        id: 'sb4_b',
        title: 'Im lặng và quan sát',
        description: 'Không muốn đối đầu trực tiếp với nền tảng',
        effects: { revenue: 0, fairness: -5 },
        riskLevel: 'low',
        consequence: 'Giữ an toàn nhưng bỏ lỡ cơ hội thay đổi',
        tags: ['defensive'],
      },
      {
        id: 'sb4_c',
        title: 'Vận động lobby qua hiệp hội',
        description: 'Tổ chức các doanh nghiệp nhỏ để gây áp lực',
        effects: { fairness: 25, publicWelfare: 10, marketShare: 15, innovation: 5 },
        riskLevel: 'medium',
        consequence: 'Tốn thời gian và công sức nhưng tác động mạnh',
        tags: ['ethical', 'balanced'],
      },
      {
        id: 'sb4_d',
        title: 'Đề xuất giải pháp công nghệ',
        description: 'Chia sẻ ý tưởng về nền tảng minh bạch hơn',
        effects: { innovation: 25, fairness: 15, userTrust: 20, publicWelfare: 10 },
        riskLevel: 'medium',
        consequence: 'Định hướng tương lai cho ngành',
        tags: ['innovation', 'ethical'],
      },
    ],
  },
  {
    roundNumber: 5,
    scenario: 'Luật mới được thông qua! Nền tảng phải tuân thủ các quy định công bằng hơn. Cơ hội mở ra cho doanh nghiệp nhỏ. Chiến lược cuối cùng?',
    choices: [
      {
        id: 'sb5_a',
        title: 'Mở rộng quy mô nhanh chóng',
        description: 'Tận dụng cơ hội để tăng trưởng mạnh',
        effects: { revenue: 25, marketShare: 20, innovation: 10, userTrust: 15 },
        riskLevel: 'medium',
        consequence: 'Tăng trưởng nhanh nhưng cần vốn lớn',
        tags: ['aggressive'],
      },
      {
        id: 'sb5_b',
        title: 'Tập trung chất lượng và thương hiệu',
        description: 'Xây dựng lòng trung thành khách hàng',
        effects: { userTrust: 25, innovation: 15, revenue: 15, marketShare: 10 },
        riskLevel: 'low',
        consequence: 'Tăng trưởng ổn định và bền vững',
        tags: ['innovation', 'defensive'],
      },
      {
        id: 'sb5_c',
        title: 'Đa dạng hóa kênh phân phối',
        description: 'Không phụ thuộc vào một nền tảng',
        effects: { marketShare: 15, revenue: 20, innovation: 10, fairness: 5 },
        riskLevel: 'medium',
        consequence: 'Giảm rủi ro phụ thuộc nền tảng',
        tags: ['balanced'],
      },
      {
        id: 'sb5_d',
        title: 'Đầu tư R&D và AI',
        description: 'Xây dựng lợi thế cạnh tranh dài hạn',
        effects: { innovation: 30, revenue: 10, userTrust: 15, marketShare: 12 },
        riskLevel: 'medium',
        consequence: 'Dẫn đầu công nghệ trong ngành',
        tags: ['innovation'],
      },
    ],
  },
];

export const PLATFORM_ROUNDS: Round[] = [
  {
    roundNumber: 1,
    scenario: 'Doanh nghiệp nhỏ phàn nàn về thuật toán tìm kiếm không công bằng. Cơ quan quản lý bắt đầu điều tra. Quyết định của bạn?',
    choices: [
      {
        id: 'pf1_a',
        title: 'Điều chỉnh thuật toán công bằng hơn',
        description: 'Tăng tính minh bạch và công bằng',
        effects: { fairness: 20, userTrust: 15, revenue: -10, marketShare: -5 },
        riskLevel: 'medium',
        consequence: 'Giảm lợi nhuận ngắn hạn nhưng cải thiện uy tín',
        tags: ['ethical'],
      },
      {
        id: 'pf1_b',
        title: 'Giữ nguyên và lobby với chính phủ',
        description: 'Bảo vệ mô hình kinh doanh hiện tại',
        effects: { revenue: 10, fairness: -15, userTrust: -20, publicWelfare: -10 },
        riskLevel: 'high',
        consequence: 'Duy trì lợi nhuận nhưng mất uy tín',
        tags: ['aggressive'],
      },
      {
        id: 'pf1_c',
        title: 'Tạo chương trình hỗ trợ doanh nghiệp nhỏ',
        description: 'Đầu tư vào việc phát triển sellers',
        effects: { fairness: 15, publicWelfare: 20, revenue: -5, userTrust: 20 },
        riskLevel: 'low',
        consequence: 'Cải thiện quan hệ với cộng đồng',
        tags: ['ethical', 'balanced'],
      },
      {
        id: 'pf1_d',
        title: 'Phát triển AI giải thích được',
        description: 'Đầu tư vào công nghệ AI minh bạch',
        effects: { innovation: 25, userTrust: 20, fairness: 15, revenue: -8 },
        riskLevel: 'medium',
        consequence: 'Tiên phong trong AI có trách nhiệm',
        tags: ['innovation', 'ethical'],
      },
    ],
  },
  {
    roundNumber: 2,
    scenario: 'Bạn phát hiện ra dữ liệu sellers có thể giúp tối ưu hóa sản phẩm riêng của nền tảng, tăng doanh thu 50%. Nhưng điều này vi phạm đạo đức. Hành động?',
    choices: [
      {
        id: 'pf2_a',
        title: 'Sử dụng dữ liệu - Tối ưu lợi nhuận',
        description: 'Ưu tiên lợi ích cổ đông',
        effects: { revenue: 30, marketShare: 20, fairness: -25, userTrust: -30 },
        riskLevel: 'high',
        consequence: 'Lợi nhuận cao nhưng rủi ro pháp lý và uy tín',
        tags: ['aggressive'],
      },
      {
        id: 'pf2_b',
        title: 'Không sử dụng - Giữ nguyên tắc',
        description: 'Tuân thủ đạo đức kinh doanh',
        effects: { fairness: 20, userTrust: 25, revenue: -10, publicWelfare: 15 },
        riskLevel: 'low',
        consequence: 'Hy sinh lợi nhuận ngắn hạn để bảo vệ thương hiệu',
        tags: ['ethical', 'defensive'],
      },
      {
        id: 'pf2_c',
        title: 'Tạo chính sách dữ liệu minh bạch',
        description: 'Công khai cách sử dụng dữ liệu',
        effects: { fairness: 15, userTrust: 20, innovation: 10, revenue: 5 },
        riskLevel: 'medium',
        consequence: 'Tăng minh bạch, xây dựng niềm tin',
        tags: ['ethical', 'innovation'],
      },
      {
        id: 'pf2_d',
        title: 'Chia sẻ lợi nhuận với sellers',
        description: 'Tạo mô hình win-win với đối tác',
        effects: { publicWelfare: 25, fairness: 20, userTrust: 18, revenue: 8 },
        riskLevel: 'low',
        consequence: 'Xây dựng hệ sinh thái bền vững',
        tags: ['ethical', 'balanced'],
      },
    ],
  },
  {
    roundNumber: 3,
    scenario: 'Đối thủ ra mắt nền tảng mới với phí thấp hơn 30%. Nhiều sellers đang cân nhắc chuyển đi. Chiến lược của bạn?',
    choices: [
      {
        id: 'pf3_a',
        title: 'Giảm phí để cạnh tranh',
        description: 'Price war - giành lại thị phần',
        effects: { marketShare: 10, revenue: -20, userTrust: 5 },
        riskLevel: 'high',
        consequence: 'Cuộc chiến giá cả, giảm lợi nhuận mạnh',
        tags: ['aggressive'],
      },
      {
        id: 'pf3_b',
        title: 'Tăng giá trị dịch vụ',
        description: 'Đầu tư vào công nghệ, logistics, marketing',
        effects: { innovation: 20, userTrust: 20, revenue: -10, marketShare: 5 },
        riskLevel: 'medium',
        consequence: 'Chi phí tăng nhưng tạo lợi thế cạnh tranh',
        tags: ['innovation', 'balanced'],
      },
      {
        id: 'pf3_c',
        title: 'Lock-in sellers bằng hợp đồng độc quyền',
        description: 'Ép buộc sellers chỉ bán trên nền tảng',
        effects: { marketShare: 15, revenue: 10, fairness: -30, userTrust: -25 },
        riskLevel: 'high',
        consequence: 'Giữ sellers nhưng vi phạm cạnh tranh',
        tags: ['aggressive'],
      },
      {
        id: 'pf3_d',
        title: 'Tạo hệ sinh thái đa dịch vụ',
        description: 'Mở rộng sang thanh toán, vận chuyển, tài chính',
        effects: { innovation: 25, marketShare: 20, revenue: 15, userTrust: 10 },
        riskLevel: 'medium',
        consequence: 'Tăng giá trị, khó rời bỏ nền tảng',
        tags: ['innovation', 'aggressive'],
      },
    ],
  },
  {
    roundNumber: 4,
    scenario: 'Cơ quan quản lý đề xuất chia tách nền tảng thành các đơn vị nhỏ để tránh độc quyền. Dư luận ủng hộ. Phản ứng của bạn?',
    choices: [
      {
        id: 'pf4_a',
        title: 'Hợp tác với cơ quan quản lý',
        description: 'Tự nguyện cải cách mô hình kinh doanh',
        effects: { fairness: 30, publicWelfare: 25, revenue: -15, userTrust: 20 },
        riskLevel: 'medium',
        consequence: 'Giảm quy mô nhưng cải thiện hình ảnh',
        tags: ['ethical', 'defensive'],
      },
      {
        id: 'pf4_b',
        title: 'Chống lại bằng lobby và pháp lý',
        description: 'Sử dụng luật sư và quan hệ chính trị',
        effects: { revenue: 10, fairness: -20, publicWelfare: -30, userTrust: -25 },
        riskLevel: 'high',
        consequence: 'Bảo vệ lợi ích nhưng mất dân tâm',
        tags: ['aggressive'],
      },
      {
        id: 'pf4_c',
        title: 'Đề xuất giải pháp tự quản',
        description: 'Cam kết minh bạch và công bằng hơn',
        effects: { fairness: 20, userTrust: 25, innovation: 15, revenue: -5 },
        riskLevel: 'low',
        consequence: 'Tránh chia tách, duy trì kiểm soát',
        tags: ['ethical', 'balanced'],
      },
      {
        id: 'pf4_d',
        title: 'Tái cấu trúc thành holding',
        description: 'Tách đơn vị nhưng vẫn giữ quyền kiểm soát',
        effects: { fairness: 15, revenue: 5, innovation: 20, marketShare: 10 },
        riskLevel: 'medium',
        consequence: 'Thỏa hiệp khôn ngoan, giữ sức mạnh',
        tags: ['balanced', 'innovation'],
      },
    ],
  },
  {
    roundNumber: 5,
    scenario: 'Luật chống độc quyền được thông qua với nhiều quy định mới. Bạn phải điều chỉnh hoạt động. Chiến lược dài hạn?',
    choices: [
      {
        id: 'pf5_a',
        title: 'Chuyển đổi thành mô hình mở',
        description: 'Tạo nền tảng trung lập, minh bạch',
        effects: { fairness: 35, publicWelfare: 30, userTrust: 30, revenue: -10, innovation: 15 },
        riskLevel: 'medium',
        consequence: 'Mất một số lợi thế nhưng bền vững dài hạn',
        tags: ['ethical', 'innovation'],
      },
      {
        id: 'pf5_b',
        title: 'Tập trung vào đổi mới công nghệ',
        description: 'Đầu tư mạnh vào AI, automation',
        effects: { innovation: 30, revenue: 15, userTrust: 20, marketShare: 10 },
        riskLevel: 'low',
        consequence: 'Tạo lợi thế cạnh tranh mới',
        tags: ['innovation'],
      },
      {
        id: 'pf5_c',
        title: 'Mở rộng ra thị trường quốc tế',
        description: 'Tìm kiếm tăng trưởng ở nước khác',
        effects: { revenue: 25, marketShare: 20, innovation: 10, fairness: -10 },
        riskLevel: 'high',
        consequence: 'Tăng trưởng nhưng gặp thách thức mới',
        tags: ['aggressive'],
      },
      {
        id: 'pf5_d',
        title: 'Đầu tư vào trách nhiệm xã hội',
        description: 'ESG, carbon neutral, hỗ trợ cộng đồng',
        effects: { publicWelfare: 35, userTrust: 30, fairness: 25, revenue: -8, innovation: 12 },
        riskLevel: 'low',
        consequence: 'Xây dựng thương hiệu bền vững',
        tags: ['ethical', 'balanced'],
      },
    ],
  },
];

export const REGULATOR_ROUNDS: Round[] = [
  {
    roundNumber: 1,
    scenario: 'Doanh nghiệp nhỏ tố cáo nền tảng lớn lạm dụng vị trí thống trị. Bạn có bằng chứng sơ bộ. Quyết định điều tra?',
    choices: [
      {
        id: 'rg1_a',
        title: 'Mở điều tra toàn diện',
        description: 'Điều tra sâu hành vi của nền tảng',
        effects: { fairness: 20, publicWelfare: 15, innovation: -5 },
        riskLevel: 'low',
        consequence: 'Tốn thời gian và nguồn lực nhưng đúng đắn',
        tags: ['ethical'],
      },
      {
        id: 'rg1_b',
        title: 'Yêu cầu nền tảng tự điều chỉnh',
        description: 'Đưa ra cảnh báo và thời hạn khắc phục',
        effects: { fairness: 10, publicWelfare: 5, userTrust: 5 },
        riskLevel: 'medium',
        consequence: 'Nhanh nhưng có thể không hiệu quả',
        tags: ['balanced'],
      },
      {
        id: 'rg1_c',
        title: 'Trì hoãn - Cần thêm bằng chứng',
        description: 'Thu thập thêm thông tin trước khi hành động',
        effects: { fairness: -10, publicWelfare: -10, userTrust: -15 },
        riskLevel: 'high',
        consequence: 'Mất lòng tin công chúng, doanh nghiệp nhỏ bị thiệt',
        tags: ['defensive'],
      },
      {
        id: 'rg1_d',
        title: 'Tổ chức họp công khai',
        description: 'Mời tất cả bên liên quan thảo luận minh bạch',
        effects: { fairness: 18, publicWelfare: 20, userTrust: 25, innovation: 5 },
        riskLevel: 'low',
        consequence: 'Tạo tiền lệ tốt về quy trình dân chủ',
        tags: ['ethical', 'balanced'],
      },
    ],
  },
  {
    roundNumber: 2,
    scenario: 'Nền tảng lobby mạnh mẽ, đe dọa cắt giảm đầu tư nếu bạn áp dụng quy định nghiêm ngặt. Nhiều việc làm có thể mất. Hành động?',
    choices: [
      {
        id: 'rg2_a',
        title: 'Kiên quyết áp dụng quy định',
        description: 'Không để bị đe dọa, ưu tiên công bằng',
        effects: { fairness: 30, publicWelfare: 20, innovation: -10, userTrust: 25 },
        riskLevel: 'high',
        consequence: 'Có thể gặp áp lực chính trị lớn',
        tags: ['ethical', 'aggressive'],
      },
      {
        id: 'rg2_b',
        title: 'Thương lượng quy định nhẹ hơn',
        description: 'Tìm điểm cân bằng giữa quy định và tăng trưởng',
        effects: { fairness: 10, publicWelfare: 10, innovation: 5 },
        riskLevel: 'medium',
        consequence: 'Thỏa hiệp nhưng ít hiệu quả hơn',
        tags: ['balanced'],
      },
      {
        id: 'rg2_c',
        title: 'Rút lui trước áp lực',
        description: 'Ưu tiên việc làm và kinh tế',
        effects: { fairness: -25, publicWelfare: -20, userTrust: -30, innovation: 10 },
        riskLevel: 'high',
        consequence: 'Bị coi là yếu đuối, mất uy tín',
        tags: ['defensive'],
      },
      {
        id: 'rg2_d',
        title: 'Áp dụng từng bước có lộ trình',
        description: 'Quy định tăng dần, cho doanh nghiệp thời gian điều chỉnh',
        effects: { fairness: 20, publicWelfare: 18, innovation: 8, userTrust: 20 },
        riskLevel: 'low',
        consequence: 'Cân bằng tốt, ít phản ứng tiêu cực',
        tags: ['balanced', 'ethical'],
      },
    ],
  },
  {
    roundNumber: 3,
    scenario: 'Phát hiện nền tảng sử dụng dữ liệu người bán trái phép để cạnh tranh. Scandal có thể làm rung chuyển thị trường. Phản ứng?',
    choices: [
      {
        id: 'rg3_a',
        title: 'Công bố ngay và phạt nặng',
        description: 'Minh bạch thông tin, xử phạt nghiêm khắc',
        effects: { fairness: 35, publicWelfare: 25, userTrust: 30, innovation: -15 },
        riskLevel: 'medium',
        consequence: 'Thị trường rung động nhưng công lý được thực thi',
        tags: ['ethical', 'aggressive'],
      },
      {
        id: 'rg3_b',
        title: 'Yêu cầu khắc phục kín đáo',
        description: 'Xử lý sau hậu trường để tránh panic',
        effects: { fairness: 15, publicWelfare: 10, userTrust: -10 },
        riskLevel: 'high',
        consequence: 'Ổn định thị trường nhưng thiếu minh bạch',
        tags: ['defensive'],
      },
      {
        id: 'rg3_c',
        title: 'Tổ chức điều trần công khai',
        description: 'Mời các bên liên quan tham gia',
        effects: { fairness: 30, publicWelfare: 30, userTrust: 25, innovation: -5 },
        riskLevel: 'low',
        consequence: 'Quy trình dân chủ, xây dựng lòng tin',
        tags: ['ethical', 'balanced'],
      },
      {
        id: 'rg3_d',
        title: 'Thiết lập cơ chế giám sát dữ liệu',
        description: 'Tạo hệ thống kiểm soát để ngăn chặn tương lai',
        effects: { fairness: 28, publicWelfare: 22, userTrust: 28, innovation: 10 },
        riskLevel: 'low',
        consequence: 'Giải pháp dài hạn, ngăn chặn tái diễn',
        tags: ['innovation', 'ethical'],
      },
    ],
  },
  {
    roundNumber: 4,
    scenario: 'Đề xuất luật mới về chống độc quyền kỹ thuật số đang được tranh luận. Nền tảng phản đối mạnh, doanh nghiệp nhỏ ủng hộ. Vai trò của bạn?',
    choices: [
      {
        id: 'rg4_a',
        title: 'Ủng hộ mạnh mẽ luật mới',
        description: 'Đẩy mạnh thông qua với quy định nghiêm ngặt',
        effects: { fairness: 40, publicWelfare: 35, userTrust: 30, innovation: -10 },
        riskLevel: 'medium',
        consequence: 'Tạo tiền lệ quan trọng cho quy định',
        tags: ['ethical', 'aggressive'],
      },
      {
        id: 'rg4_b',
        title: 'Đề xuất phiên bản nhẹ hơn',
        description: 'Cân bằng giữa quy định và phát triển',
        effects: { fairness: 20, publicWelfare: 20, innovation: 5, userTrust: 15 },
        riskLevel: 'low',
        consequence: 'Thỏa hiệp, dễ thông qua hơn',
        tags: ['balanced'],
      },
      {
        id: 'rg4_c',
        title: 'Trung lập - Để quốc hội quyết',
        description: 'Không can thiệp vào quá trình chính trị',
        effects: { fairness: 5, publicWelfare: 5, userTrust: -10 },
        riskLevel: 'medium',
        consequence: 'Tránh tranh cãi nhưng bị coi là thụ động',
        tags: ['defensive'],
      },
      {
        id: 'rg4_d',
        title: 'Tổ chức hội thảo đa bên',
        description: 'Tạo diễn đàn cho tất cả bên góp ý',
        effects: { fairness: 25, publicWelfare: 28, userTrust: 28, innovation: 10 },
        riskLevel: 'low',
        consequence: 'Quyết định dựa trên đồng thuận',
        tags: ['ethical', 'balanced'],
      },
    ],
  },
  {
    roundNumber: 5,
    scenario: 'Luật được thông qua! Bạn chịu trách nhiệm thực thi. Cần xây dựng framework giám sát. Cách tiếp cận?',
    choices: [
      {
        id: 'rg5_a',
        title: 'Tạo cơ quan giám sát độc lập',
        description: 'Thành lập đơn vị chuyên trách với quyền lực mạnh',
        effects: { fairness: 45, publicWelfare: 40, userTrust: 35, innovation: -5 },
        riskLevel: 'low',
        consequence: 'Giám sát chặt chẽ, đảm bảo tuân thủ',
        tags: ['ethical'],
      },
      {
        id: 'rg5_b',
        title: 'Hợp tác với industry tự quản',
        description: 'Để ngành tự xây dựng quy chuẩn',
        effects: { fairness: 20, publicWelfare: 15, innovation: 15, userTrust: 10 },
        riskLevel: 'high',
        consequence: 'Linh hoạt nhưng có thể thiếu răn đe',
        tags: ['balanced'],
      },
      {
        id: 'rg5_c',
        title: 'Framework lai giữa kiểm soát và đổi mới',
        description: 'Cân bằng giám sát và khuyến khích đổi mới',
        effects: { fairness: 35, publicWelfare: 30, innovation: 20, userTrust: 30 },
        riskLevel: 'medium',
        consequence: 'Tiếp cận tối ưu, bền vững dài hạn',
        tags: ['balanced', 'innovation'],
      },
      {
        id: 'rg5_d',
        title: 'Áp dụng công nghệ AI để giám sát',
        description: 'Sử dụng automation và AI cho giám sát real-time',
        effects: { fairness: 38, publicWelfare: 35, innovation: 30, userTrust: 32 },
        riskLevel: 'low',
        consequence: 'Hiện đại, hiệu quả, minh bạch',
        tags: ['innovation', 'ethical'],
      },
    ],
  },
];

// Map vai trò với rounds tương ứng
export const ROUNDS_BY_ROLE: Record<string, Round[]> = {
  smallbiz: SMALLBIZ_ROUNDS,
  platform: PLATFORM_ROUNDS,
  regulator: REGULATOR_ROUNDS,
};

// Shuffle array utility using Fisher-Yates algorithm
const shuffleArray = <T>(array: T[]): T[] => {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};

// Get rounds with randomized scenarios and shuffled choice positions
export const getShuffledRounds = (role: string): Round[] => {
  const baseRounds = ROUNDS_BY_ROLE[role] || [];
  
  return baseRounds.map((baseRound, index) => {
    const roundNumber = index + 1;
    
    // Check if variations exist for this round
    let variations: Round[] = [];
    if (role === 'smallbiz' && SMALLBIZ_ROUND_VARIATIONS[roundNumber]) {
      variations = SMALLBIZ_ROUND_VARIATIONS[roundNumber];
    } else if (role === 'platform' && PLATFORM_ROUND_VARIATIONS[roundNumber]) {
      variations = PLATFORM_ROUND_VARIATIONS[roundNumber];
    } else if (role === 'regulator' && REGULATOR_ROUND_VARIATIONS[roundNumber]) {
      variations = REGULATOR_ROUND_VARIATIONS[roundNumber];
    }
    
    // Combine base round with variations to create pool of possible scenarios
    const allPossibleRounds = [baseRound, ...variations];
    
    // Randomly pick one scenario from the pool
    const selectedRound = allPossibleRounds[Math.floor(Math.random() * allPossibleRounds.length)];
    
    // Shuffle choices within the selected round
    return {
      ...selectedRound,
      choices: shuffleArray(selectedRound.choices),
    };
  });
};

// Alternative scenarios for variation (randomly picked per game)
export const SMALLBIZ_ROUND_VARIATIONS: Record<number, Round[]> = {
  1: [
    {
      roundNumber: 1,
      scenario: 'Nền tảng lớn bắt đầu áp dụng chính sách ưu tiên sản phẩm của họ trong kết quả tìm kiếm. Doanh số của bạn giảm 30%. Bạn sẽ làm gì?',
      choices: SMALLBIZ_ROUNDS[0].choices,
    },
    {
      roundNumber: 1,
      scenario: 'Một đối thủ lớn vừa mở cửa hàng bán cùng sản phẩm với giá thấp hơn 20%. Khách hàng bắt đầu rời bỏ. Chiến lược đầu tiên của bạn?',
      choices: [
        {
          id: 'sb1_alt_a',
          title: 'Tập trung vào chất lượng cao cấp',
          description: 'Nâng cấp sản phẩm, nhấn mạnh chất lượng vượt trội',
          effects: { userTrust: 20, innovation: 15, revenue: 5, marketShare: -5 },
          riskLevel: 'medium',
          consequence: 'Khách hàng sẵn sàng trả giá cao hơn cho chất lượng',
          tags: ['innovation', 'ethical'],
        },
        {
          id: 'sb1_alt_b',
          title: 'Chiến dịch marketing viral',
          description: 'Đầu tư mạnh vào social media và PR',
          effects: { marketShare: 15, revenue: -10, userTrust: 10, innovation: 5 },
          riskLevel: 'medium',
          consequence: 'Tăng nhận diện thương hiệu nhanh chóng',
          tags: ['aggressive', 'innovation'],
        },
        {
          id: 'sb1_alt_c',
          title: 'Chương trình loyalty độc đáo',
          description: 'Tạo hệ thống điểm thưởng và quyền lợi đặc biệt',
          effects: { userTrust: 25, revenue: 10, marketShare: 8, innovation: 8 },
          riskLevel: 'low',
          consequence: 'Giữ chân khách hàng trung thành lâu dài',
          tags: ['defensive', 'balanced'],
        },
        {
          id: 'sb1_alt_d',
          title: 'Đàm phán độc quyền với nhà cung cấp',
          description: 'Đảm bảo nguồn hàng độc quyền chất lượng cao',
          effects: { innovation: 20, marketShare: 12, revenue: -5, fairness: -5 },
          riskLevel: 'high',
          consequence: 'Sản phẩm độc đáo nhưng có thể gây tranh cãi',
          tags: ['aggressive', 'innovation'],
        },
      ],
    },
    {
      roundNumber: 1,
      scenario: 'Influencer nổi tiếng livestream bán hàng fake gần giống sản phẩm của bạn. Hàng ngàn người mua nhầm. Danh tiếng bị ảnh hưởng. Hành động gấp?',
      choices: [
        {
          id: 'sb1_alt2_a',
          title: 'Báo cáo vi phạm bản quyền',
          description: 'Liên hệ nền tảng và cơ quan pháp luật',
          effects: { fairness: 20, userTrust: 10, revenue: -5, marketShare: 5 },
          riskLevel: 'medium',
          consequence: 'Bảo vệ thương hiệu nhưng mất thời gian',
          tags: ['ethical', 'defensive'],
        },
        {
          id: 'sb1_alt2_b',
          title: 'Làm video so sánh chất lượng',
          description: 'Viral marketing phơi bày hàng fake trên social media',
          effects: { userTrust: 25, marketShare: 15, innovation: 10, revenue: 5 },
          riskLevel: 'medium',
          consequence: 'PR tốt, tăng nhận thức về hàng thật',
          tags: ['aggressive', 'innovation'],
        },
        {
          id: 'sb1_alt2_c',
          title: 'Hợp tác với influencer khác',
          description: 'Tìm KOL uy tín để endorse sản phẩm chính hãng',
          effects: { userTrust: 20, revenue: -10, marketShare: 18, innovation: 8 },
          riskLevel: 'low',
          consequence: 'Xây dựng mạng lưới PR bền vững',
          tags: ['balanced', 'innovation'],
        },
        {
          id: 'sb1_alt2_d',
          title: 'Chương trình "Nhận diện hàng thật"',
          description: 'Hướng dẫn khách hàng phân biệt chính hãng',
          effects: { userTrust: 30, publicWelfare: 15, innovation: 10, marketShare: 10 },
          riskLevel: 'low',
          consequence: 'Giáo dục khách hàng, xây dựng lòng tin dài hạn',
          tags: ['ethical', 'balanced'],
        },
      ],
    },
  ],
  2: [
    {
      roundNumber: 2,
      scenario: 'Nền tảng công bố chính sách thu phí cao hơn 20% cho sellers. Bạn có nhiều đơn hàng nhưng lợi nhuận bị ép. Quyết định của bạn?',
      choices: SMALLBIZ_ROUNDS[1].choices,
    },
    {
      roundNumber: 2,
      scenario: 'Chi phí nguyên liệu tăng đột biến 35% do khủng hoảng chuỗi cung ứng. Nếu không điều chỉnh giá, bạn sẽ lỗ. Bạn làm gì?',
      choices: [
        {
          id: 'sb2_alt_a',
          title: 'Tăng giá bán minh bạch',
          description: 'Giải thích rõ lý do tăng giá cho khách hàng',
          effects: { userTrust: 10, revenue: 10, marketShare: -8, fairness: 10 },
          riskLevel: 'medium',
          consequence: 'Khách hàng hiểu nhưng một số sẽ rời đi',
          tags: ['ethical', 'balanced'],
        },
        {
          id: 'sb2_alt_b',
          title: 'Tìm nhà cung cấp thay thế',
          description: 'Chuyển sang nguồn nguyên liệu giá rẻ hơn',
          effects: { revenue: 15, marketShare: 10, userTrust: -10, innovation: -5 },
          riskLevel: 'high',
          consequence: 'Giảm chi phí nhưng có thể ảnh hưởng chất lượng',
          tags: ['aggressive'],
        },
        {
          id: 'sb2_alt_c',
          title: 'Thu hẹp sản phẩm chủ lực',
          description: 'Chỉ bán những mặt hàng lợi nhuận cao nhất',
          effects: { revenue: 20, marketShare: -10, innovation: 10, userTrust: 5 },
          riskLevel: 'medium',
          consequence: 'Tập trung hiệu quả, cắt bỏ sản phẩm kém',
          tags: ['balanced', 'innovation'],
        },
        {
          id: 'sb2_alt_d',
          title: 'Đầu tư tự động hóa',
          description: 'Giảm chi phí vận hành bằng công nghệ',
          effects: { innovation: 25, revenue: -15, marketShare: 5, userTrust: 10 },
          riskLevel: 'high',
          consequence: 'Chi phí ban đầu cao, tiết kiệm dài hạn',
          tags: ['innovation'],
        },
      ],
    },
    {
      roundNumber: 2,
      scenario: 'Review bombing! Đối thủ thuê người đánh giá 1 sao hàng loạt cho shop của bạn. Rating giảm từ 4.8 xuống 3.2. Khách hàng nghi ngờ. Xử lý khủng hoảng?',
      choices: [
        {
          id: 'sb2_alt2_a',
          title: 'Báo cáo nền tảng về review fake',
          description: 'Thu thập bằng chứng và yêu cầu xóa review gian lận',
          effects: { fairness: 20, userTrust: 15, revenue: -5, marketShare: 5 },
          riskLevel: 'medium',
          consequence: 'Quá trình chậm nhưng làm sạch danh tiếng',
          tags: ['ethical', 'defensive'],
        },
        {
          id: 'sb2_alt2_b',
          title: 'Chương trình "Đổi review lấy quà"',
          description: 'Khuyến khích khách thật để lại đánh giá tích cực',
          effects: { userTrust: 25, revenue: -15, marketShare: 15, innovation: 5 },
          riskLevel: 'low',
          consequence: 'Chi phí cao nhưng rebuild trust nhanh',
          tags: ['balanced'],
        },
        {
          id: 'sb2_alt2_c',
          title: 'Video response trên social media',
          description: 'CEO trực tiếp giải thích và show quy trình sản xuất',
          effects: { userTrust: 30, innovation: 15, revenue: 5, marketShare: 12 },
          riskLevel: 'low',
          consequence: 'Minh bạch, tạo kết nối với khách hàng',
          tags: ['ethical', 'innovation'],
        },
        {
          id: 'sb2_alt2_d',
          title: 'Khuyến mãi sốc - Chứng minh bằng hành động',
          description: 'Giảm giá 50% + cam kết đổi trả miễn phí',
          effects: { revenue: -20, marketShare: 25, userTrust: 15, innovation: 5 },
          riskLevel: 'high',
          consequence: 'Mất lợi nhuận ngắn hạn, giành lại niềm tin',
          tags: ['aggressive'],
        },
      ],
    },
  ],
  3: [
    {
      roundNumber: 3,
      scenario: 'Nền tảng ra mắt sản phẩm cạnh tranh trực tiếp với bạn, sử dụng dữ liệu bán hàng của bạn để tối ưu hóa. Thị phần giảm 40%. Hành động?',
      choices: SMALLBIZ_ROUNDS[2].choices,
    },
    {
      roundNumber: 3,
      scenario: 'Một đối thủ mới xuất hiện với công nghệ AI tiên tiến, cung cấp dịch vụ khách hàng tự động 24/7. Khách hàng của bạn bắt đầu chuyển sang. Bạn phản ứng thế nào?',
      choices: [
        {
          id: 'sb3_alt_a',
          title: 'Hợp tác với startup AI',
          description: 'Đầu tư vào giải pháp AI cho dịch vụ khách hàng',
          effects: { innovation: 20, revenue: -10, userTrust: 15, marketShare: 10 },
          riskLevel: 'medium',
          consequence: 'Chi phí đầu tư cao nhưng nâng cao trải nghiệm',
          tags: ['innovation', 'balanced'],
        },
        {
          id: 'sb3_alt_b',
          title: 'Tập trung vào dịch vụ con người',
          description: 'Nhấn mạnh sự tương tác cá nhân hóa',
          effects: { userTrust: 25, revenue: 5, marketShare: 5, innovation: -5 },
          riskLevel: 'low',
          consequence: 'Tạo lợi thế khác biệt với cảm xúc con người',
          tags: ['defensive', 'ethical'],
        },
        {
          id: 'sb3_alt_c',
          title: 'Giảm giá để giữ khách',
          description: 'Cạnh tranh bằng mức giá thấp hơn',
          effects: { revenue: -15, marketShare: 10, userTrust: -5, fairness: -5 },
          riskLevel: 'high',
          consequence: 'Lợi nhuận giảm mạnh, khó bền vững',
          tags: ['aggressive'],
        },
        {
          id: 'sb3_alt_d',
          title: 'Xây dựng hệ sinh thái đối tác',
          description: 'Liên kết với các doanh nghiệp nhỏ khác',
          effects: { marketShare: 15, innovation: 12, fairness: 10, userTrust: 10 },
          riskLevel: 'medium',
          consequence: 'Tạo mạng lưới mạnh mẽ để cạnh tranh',
          tags: ['innovation', 'balanced'],
        },
      ],
    },
    {
      roundNumber: 3,
      scenario: 'Khách hàng lớn nhất của bạn (chiếm 40% doanh thu) yêu cầu giảm giá 30% hoặc sẽ chuyển sang đối thủ. Bạn phụ thuộc quá nhiều vào họ. Quyết định?',
      choices: [
        {
          id: 'sb3_alt2_a',
          title: 'Chấp nhận giảm giá',
          description: 'Giữ khách hàng lớn, hy sinh lợi nhuận',
          effects: { revenue: -20, marketShare: 10, userTrust: 5, fairness: -5 },
          riskLevel: 'high',
          consequence: 'Duy trì doanh thu nhưng lợi nhuận giảm mạnh',
          tags: ['defensive'],
        },
        {
          id: 'sb3_alt2_b',
          title: 'Từ chối và đa dạng hóa',
          description: 'Chấp nhận mất khách, tìm nhiều khách nhỏ hơn',
          effects: { revenue: -25, marketShare: -15, innovation: 20, fairness: 15 },
          riskLevel: 'high',
          consequence: 'Khó khăn ngắn hạn, độc lập dài hạn',
          tags: ['ethical', 'innovation'],
        },
        {
          id: 'sb3_alt2_c',
          title: 'Đàm phán giá trị gia tăng',
          description: 'Đề xuất dịch vụ cao cấp thay vì giảm giá',
          effects: { revenue: 10, innovation: 20, userTrust: 15, marketShare: 8 },
          riskLevel: 'medium',
          consequence: 'Win-win, tạo thêm giá trị cho cả hai bên',
          tags: ['balanced', 'innovation'],
        },
        {
          id: 'sb3_alt2_d',
          title: 'Ký hợp đồng dài hạn với commitment',
          description: 'Giảm 15% đổi lại cam kết 3 năm',
          effects: { revenue: -10, marketShare: 15, userTrust: 20, fairness: 10 },
          riskLevel: 'low',
          consequence: 'Ổn định dài hạn, dự đoán được cash flow',
          tags: ['balanced', 'defensive'],
        },
      ],
    },
  ],
  4: [
    {
      roundNumber: 4,
      scenario: 'Cơ quan quản lý đề xuất luật mới hạn chế hành vi độc quyền của nền tảng. Bạn được mời tham gia điều trần. Lựa chọn của bạn?',
      choices: SMALLBIZ_ROUNDS[3].choices,
    },
    {
      roundNumber: 4,
      scenario: 'Một tập đoàn lớn đề nghị mua lại công ty của bạn với giá cao gấp 10 lần. Nhưng bạn sẽ mất quyền kiểm soát. Quyết định của bạn?',
      choices: [
        {
          id: 'sb4_alt_a',
          title: 'Chấp nhận thương vụ',
          description: 'Bán công ty và trở thành nhân viên cấp cao',
          effects: { revenue: 50, marketShare: -20, innovation: -10, fairness: -15 },
          riskLevel: 'high',
          consequence: 'Lợi nhuận lớn nhưng mất tầm nhìn ban đầu',
          tags: ['aggressive'],
        },
        {
          id: 'sb4_alt_b',
          title: 'Từ chối và giữ độc lập',
          description: 'Tiếp tục phát triển theo cách của mình',
          effects: { userTrust: 20, innovation: 15, revenue: 5, fairness: 10 },
          riskLevel: 'medium',
          consequence: 'Tự do nhưng tăng trưởng chậm hơn',
          tags: ['ethical', 'defensive'],
        },
        {
          id: 'sb4_alt_c',
          title: 'Đàm phán điều khoản tốt hơn',
          description: 'Yêu cầu giữ quyền quyết định quan trọng',
          effects: { revenue: 30, marketShare: 10, innovation: 10, fairness: 5 },
          riskLevel: 'medium',
          consequence: 'Cân bằng giữa vốn và quyền kiểm soát',
          tags: ['balanced'],
        },
        {
          id: 'sb4_alt_d',
          title: 'Gọi vốn từ nhiều nhà đầu tư nhỏ',
          description: 'Crowdfunding và venture capital độc lập',
          effects: { innovation: 20, userTrust: 15, revenue: 15, publicWelfare: 10 },
          riskLevel: 'low',
          consequence: 'Giữ được tầm nhìn và cộng đồng ủng hộ',
          tags: ['innovation', 'ethical'],
        },
      ],
    },
    {
      roundNumber: 4,
      scenario: 'Nhân viên xuất sắc nhất của bạn được BigTech săn đón với mức lương gấp 3. Team sắp tan rã nếu không giữ được họ. Làm sao?',
      choices: [
        {
          id: 'sb4_alt2_a',
          title: 'Tăng lương + cổ phần công ty',
          description: 'Chia sẻ ownership, biến nhân viên thành co-founders',
          effects: { revenue: -15, innovation: 25, userTrust: 20, fairness: 20 },
          riskLevel: 'low',
          consequence: 'Giữ được tài năng, xây dựng văn hóa ownership',
          tags: ['ethical', 'balanced'],
        },
        {
          id: 'sb4_alt2_b',
          title: 'Để họ đi, tuyển fresh graduates',
          description: 'Chấp nhận mất người giỏi, train người mới',
          effects: { revenue: -10, innovation: -10, marketShare: -5, fairness: 10 },
          riskLevel: 'high',
          consequence: 'Tiết kiệm chi phí nhưng mất kinh nghiệm',
          tags: ['aggressive', 'defensive'],
        },
        {
          id: 'sb4_alt2_c',
          title: 'Remote work + flexible benefits',
          description: 'Work-life balance, sáng tạo package benefits độc đáo',
          effects: { innovation: 20, userTrust: 15, revenue: -8, publicWelfare: 15 },
          riskLevel: 'low',
          consequence: 'Thu hút tài năng bằng môi trường, không chỉ lương',
          tags: ['innovation', 'ethical'],
        },
        {
          id: 'sb4_alt2_d',
          title: 'Hợp tác với BigTech',
          description: 'Nhân viên làm part-time cho cả hai, knowledge sharing',
          effects: { innovation: 30, revenue: 5, marketShare: 10, fairness: 15 },
          riskLevel: 'medium',
          consequence: 'Win-win-win: Nhân viên, bạn, và BigTech đều lợi',
          tags: ['innovation', 'balanced'],
        },
      ],
    },
  ],
  5: [
    {
      roundNumber: 5,
      scenario: 'Luật mới được thông qua! Nền tảng phải tuân thủ các quy định công bằng hơn. Cơ hội mở ra cho doanh nghiệp nhỏ. Chiến lược cuối cùng?',
      choices: SMALLBIZ_ROUNDS[4].choices,
    },
    {
      roundNumber: 5,
      scenario: 'Bạn đã vượt qua khó khăn! Giờ là lúc quyết định tương lai: Scale up mạnh mẽ hay phát triển bền vững? Định hình di sản của mình!',
      choices: [
        {
          id: 'sb5_alt_a',
          title: 'IPO - Niêm yết công khai',
          description: 'Ra mắt thị trường chứng khoán, gọi vốn lớn',
          effects: { revenue: 40, marketShare: 25, innovation: 15, fairness: -10 },
          riskLevel: 'high',
          consequence: 'Trở thành công ty đại chúng, áp lực lợi nhuận cao',
          tags: ['aggressive'],
        },
        {
          id: 'sb5_alt_b',
          title: 'Mô hình B Corp - Doanh nghiệp xã hội',
          description: 'Cam kết cân bằng lợi nhuận và tác động xã hội',
          effects: { userTrust: 30, publicWelfare: 25, fairness: 20, innovation: 15 },
          riskLevel: 'low',
          consequence: 'Được tôn vinh về trách nhiệm xã hội',
          tags: ['ethical', 'innovation'],
        },
        {
          id: 'sb5_alt_c',
          title: 'Franchise - Nhượng quyền thương hiệu',
          description: 'Mở rộng nhanh thông qua hệ thống nhượng quyền',
          effects: { marketShare: 30, revenue: 25, innovation: 10, userTrust: 10 },
          riskLevel: 'medium',
          consequence: 'Tăng trưởng nhanh nhưng kiểm soát chất lượng khó',
          tags: ['aggressive', 'balanced'],
        },
        {
          id: 'sb5_alt_d',
          title: 'Cooperative - Hợp tác xã',
          description: 'Chia sẻ quyền sở hữu với nhân viên và đối tác',
          effects: { fairness: 30, userTrust: 25, publicWelfare: 20, innovation: 15 },
          riskLevel: 'low',
          consequence: 'Mô hình bền vững, tạo giá trị dài hạn',
          tags: ['ethical', 'balanced'],
        },
      ],
    },
    {
      roundNumber: 5,
      scenario: 'Thành công rực rỡ! Bạn đã xây dựng brand mạnh. Giờ các đối tác quốc tế muốn hợp tác. Go global hay focus Việt Nam? Tầm nhìn cuối cùng?',
      choices: [
        {
          id: 'sb5_alt2_a',
          title: 'Mở rộng toàn Đông Nam Á',
          description: 'Chinh phục thị trường ASEAN với sản phẩm Việt',
          effects: { marketShare: 35, revenue: 30, innovation: 20, fairness: 10 },
          riskLevel: 'high',
          consequence: 'Đưa thương hiệu Việt ra thế giới',
          tags: ['aggressive', 'innovation'],
        },
        {
          id: 'sb5_alt2_b',
          title: 'Trở thành "Local Hero"',
          description: 'Tập trung làm sâu thị trường Việt Nam',
          effects: { userTrust: 35, publicWelfare: 30, fairness: 25, innovation: 20 },
          riskLevel: 'low',
          consequence: 'Biểu tượng doanh nghiệp Việt thành công',
          tags: ['ethical', 'defensive'],
        },
        {
          id: 'sb5_alt2_c',
          title: 'Ecosystem Builder',
          description: 'Đầu tư vào các startup nhỏ khác, xây dựng cộng đồng',
          effects: { fairness: 35, innovation: 30, publicWelfare: 25, userTrust: 20 },
          riskLevel: 'low',
          consequence: 'Mentor thế hệ entrepreneur tiếp theo',
          tags: ['ethical', 'innovation'],
        },
        {
          id: 'sb5_alt2_d',
          title: 'Omnichannel Transformation',
          description: 'Tích hợp online-offline, AR/VR shopping experience',
          effects: { innovation: 40, marketShare: 25, revenue: 20, userTrust: 20 },
          riskLevel: 'medium',
          consequence: 'Dẫn đầu xu hướng retail 4.0',
          tags: ['innovation', 'balanced'],
        },
      ],
    },
  ],
};

export const PLATFORM_ROUND_VARIATIONS: Record<number, Round[]> = {
  1: [
    {
      roundNumber: 1,
      scenario: 'Bạn là nền tảng số 1 thị trường! Nhưng startup mới với công nghệ AI đột phá đang thu hút đầu tư khủng. Phản ứng đầu tiên?',
      choices: PLATFORM_ROUNDS[0].choices,
    },
    {
      roundNumber: 1,
      scenario: 'Chính phủ vừa công bố dự thảo luật thuế số 15% doanh thu. Giới công nghệ phản đối mạnh mẽ. Lập trường của bạn?',
      choices: [
        {
          id: 'pf1_alt_a',
          title: 'Chấp nhận và hợp tác',
          description: 'Đồng ý đóng thuế, nhấn mạnh trách nhiệm công dân',
          effects: { publicWelfare: 20, fairness: 15, revenue: -15, userTrust: 10 },
          riskLevel: 'low',
          consequence: 'Tạo thiện cảm với chính phủ và người dân',
          tags: ['ethical'],
        },
        {
          id: 'pf1_alt_b',
          title: 'Đàm phán giảm thuế suất',
          description: 'Lobby để giảm xuống 5-7%, cam kết đầu tư STEM',
          effects: { revenue: -8, innovation: 15, publicWelfare: 10, fairness: 5 },
          riskLevel: 'medium',
          consequence: 'Thỏa hiệp, cân bằng lợi ích hai bên',
          tags: ['balanced'],
        },
        {
          id: 'pf1_alt_c',
          title: 'Phản đối công khai',
          description: 'Tuyên bố sẽ cắt giảm đầu tư nếu luật thông qua',
          effects: { revenue: 15, fairness: -20, publicWelfare: -15, marketShare: 5 },
          riskLevel: 'high',
          consequence: 'Tránh thuế nhưng mất uy tín công chúng',
          tags: ['aggressive'],
        },
        {
          id: 'pf1_alt_d',
          title: 'Đề xuất thuế lũy tiến',
          description: 'Chỉ đánh thuế cao vào doanh thu trên ngưỡng',
          effects: { fairness: 20, publicWelfare: 15, innovation: 10, revenue: -10 },
          riskLevel: 'low',
          consequence: 'Giải pháp công bằng, bảo vệ startup nhỏ',
          tags: ['ethical', 'balanced'],
        },
      ],
    },
  ],
  2: [
    {
      roundNumber: 2,
      scenario: 'Startup mới tạo ra sản phẩm sáng tạo đang thu hút nhiều người dùng trẻ. Thị phần của bạn bị ảnh hưởng. Chiến lược?',
      choices: PLATFORM_ROUNDS[1].choices,
    },
    {
      roundNumber: 2,
      scenario: 'Dữ liệu người dùng của bạn bị rò rỉ do lỗ hổng bảo mật. Media đưa tin tiêu cực. Niềm tin giảm 40%. Xử lý khủng hoảng thế nào?',
      choices: [
        {
          id: 'pf2_alt_a',
          title: 'Công khai xin lỗi và bồi thường',
          description: 'Thừa nhận sai lầm và đền bù cho người dùng',
          effects: { userTrust: 15, revenue: -20, fairness: 15, publicWelfare: 10 },
          riskLevel: 'high',
          consequence: 'Chi phí lớn nhưng phục hồi lòng tin',
          tags: ['ethical'],
        },
        {
          id: 'pf2_alt_b',
          title: 'Đổ lỗi cho bên thứ ba',
          description: 'Nói rằng đối tác bảo mật có vấn đề',
          effects: { userTrust: -15, fairness: -20, revenue: 5, marketShare: -10 },
          riskLevel: 'high',
          consequence: 'Tránh trách nhiệm nhưng mất uy tín dài hạn',
          tags: ['aggressive'],
        },
        {
          id: 'pf2_alt_c',
          title: 'Đầu tư mạnh vào bảo mật',
          description: 'Nâng cấp hệ thống an ninh toàn diện',
          effects: { userTrust: 20, innovation: 15, revenue: -15, fairness: 10 },
          riskLevel: 'medium',
          consequence: 'Chi phí cao nhưng ngăn chặn sự cố tương lai',
          tags: ['innovation', 'ethical'],
        },
        {
          id: 'pf2_alt_d',
          title: 'Im lặng và để scandal qua đi',
          description: 'Không phản hồi, chờ dư luận quên đi',
          effects: { userTrust: -25, fairness: -15, revenue: 10, marketShare: -5 },
          riskLevel: 'high',
          consequence: 'Tránh chi phí nhưng tổn hại uy tín nghiêm trọng',
          tags: ['aggressive'],
        },
      ],
    },
  ],
  3: [
    {
      roundNumber: 3,
      scenario: 'Chính phủ đề xuất chia tách nền tảng của bạn thành các công ty nhỏ hơn. Họ cáo buộc bạn độc quyền. Đáp trả như thế nào?',
      choices: PLATFORM_ROUNDS[2].choices,
    },
    {
      roundNumber: 3,
      scenario: 'Xu hướng Web3 và Blockchain đang bùng nổ. Người dùng yêu cầu nền tảng phi tập trung. Bạn có nên chuyển đổi không?',
      choices: [
        {
          id: 'pf3_alt_a',
          title: 'Chuyển đổi hoàn toàn sang Web3',
          description: 'Rebuild nền tảng trên blockchain, DAO governance',
          effects: { innovation: 35, userTrust: 20, revenue: -25, fairness: 20 },
          riskLevel: 'high',
          consequence: 'Đột phá công nghệ nhưng rủi ro kỹ thuật cao',
          tags: ['innovation', 'ethical'],
        },
        {
          id: 'pf3_alt_b',
          title: 'Hybrid - Kết hợp Web2 và Web3',
          description: 'Giữ nền tảng hiện tại, thêm tính năng blockchain',
          effects: { innovation: 25, revenue: -10, userTrust: 15, marketShare: 10 },
          riskLevel: 'medium',
          consequence: 'Cân bằng đổi mới và ổn định',
          tags: ['balanced', 'innovation'],
        },
        {
          id: 'pf3_alt_c',
          title: 'Quan sát và chờ đợi',
          description: 'Chưa đầu tư, theo dõi thị trường phát triển',
          effects: { revenue: 10, marketShare: -15, innovation: -10, userTrust: -10 },
          riskLevel: 'medium',
          consequence: 'An toàn nhưng có thể bỏ lỡ cơ hội',
          tags: ['defensive'],
        },
        {
          id: 'pf3_alt_d',
          title: 'Mua lại startup Web3',
          description: 'Acquire các công ty blockchain tiềm năng',
          effects: { innovation: 30, revenue: -15, marketShare: 15, fairness: -5 },
          riskLevel: 'medium',
          consequence: 'Nhanh chóng có công nghệ nhưng tốn kém',
          tags: ['aggressive', 'innovation'],
        },
      ],
    },
  ],
  4: [
    {
      roundNumber: 4,
      scenario: 'EU thông qua Digital Markets Act, buộc bạn mở API cho đối thủ. Tuân thủ hay kháng cáo?',
      choices: PLATFORM_ROUNDS[3].choices,
    },
    {
      roundNumber: 4,
      scenario: 'AI của bạn bị phát hiện có bias phân biệt chủng tộc và giới tính. Tổ chức nhân quyền phản đối. Giải quyết thế nào?',
      choices: [
        {
          id: 'pf4_alt_a',
          title: 'Audit độc lập và công bố',
          description: 'Mời tổ chức thứ ba kiểm tra, công khai kết quả',
          effects: { fairness: 25, userTrust: 20, innovation: 10, revenue: -10 },
          riskLevel: 'medium',
          consequence: 'Minh bạch, xây dựng lại uy tín',
          tags: ['ethical', 'balanced'],
        },
        {
          id: 'pf4_alt_b',
          title: 'Đào tạo lại AI với diverse data',
          description: 'Thu thập dữ liệu đa dạng, train lại model',
          effects: { innovation: 25, fairness: 20, userTrust: 15, revenue: -15 },
          riskLevel: 'medium',
          consequence: 'Giải quyết gốc rễ vấn đề',
          tags: ['innovation', 'ethical'],
        },
        {
          id: 'pf4_alt_c',
          title: 'Lập team AI Ethics chuyên trách',
          description: 'Tạo bộ phận giám sát đạo đức AI',
          effects: { fairness: 30, publicWelfare: 15, innovation: 15, revenue: -5 },
          riskLevel: 'low',
          consequence: 'Phòng ngừa dài hạn, cải thiện văn hóa',
          tags: ['ethical'],
        },
        {
          id: 'pf4_alt_d',
          title: 'Bác bỏ và bảo vệ thuật toán',
          description: 'Nói rằng AI chỉ phản ánh dữ liệu thực tế',
          effects: { revenue: 10, fairness: -25, userTrust: -20, publicWelfare: -15 },
          riskLevel: 'high',
          consequence: 'Tránh chi phí nhưng khủng hoảng PR nghiêm trọng',
          tags: ['aggressive'],
        },
      ],
    },
  ],
  5: [
    {
      roundNumber: 5,
      scenario: 'Bạn đã trở thành gã khổng lồ công nghệ! Giờ quyết định định hình tương lai digital của xã hội. Di sản của bạn sẽ là gì?',
      choices: PLATFORM_ROUNDS[4].choices,
    },
    {
      roundNumber: 5,
      scenario: 'Metaverse đang trở thành hiện thực. Bạn có cơ hội xây dựng thế giới ảo thống trị. Tầm nhìn cuối cùng?',
      choices: [
        {
          id: 'pf5_alt_a',
          title: 'Open Metaverse Foundation',
          description: 'Tạo metaverse mở, interoperable, phi tập trung',
          effects: { fairness: 35, innovation: 30, userTrust: 25, revenue: 15 },
          riskLevel: 'medium',
          consequence: 'Trở thành người dẫn đầu ethical tech',
          tags: ['ethical', 'innovation'],
        },
        {
          id: 'pf5_alt_b',
          title: 'Proprietary Metaverse',
          description: 'Xây dựng thế giới ảo độc quyền, kiểm soát hoàn toàn',
          effects: { revenue: 50, marketShare: 40, fairness: -25, publicWelfare: -20 },
          riskLevel: 'high',
          consequence: 'Lợi nhuận khủng nhưng bị chỉ trích độc quyền',
          tags: ['aggressive'],
        },
        {
          id: 'pf5_alt_c',
          title: 'Social Impact Metaverse',
          description: 'Metaverse phục vụ giáo dục, y tế, văn hóa',
          effects: { publicWelfare: 40, fairness: 30, innovation: 25, userTrust: 30 },
          riskLevel: 'low',
          consequence: 'Di sản nhân văn, được tôn vinh',
          tags: ['ethical'],
        },
        {
          id: 'pf5_alt_d',
          title: 'Hybrid Reality Platform',
          description: 'Kết nối thế giới thật và ảo seamlessly',
          effects: { innovation: 40, revenue: 30, marketShare: 25, userTrust: 20 },
          riskLevel: 'medium',
          consequence: 'Đổi mới đột phá, định hình tương lai',
          tags: ['innovation', 'balanced'],
        },
      ],
    },
  ],
};

export const REGULATOR_ROUND_VARIATIONS: Record<number, Round[]> = {
  1: [
    {
      roundNumber: 1,
      scenario: 'Nền tảng lớn bị tố cáo lạm dụng dữ liệu người dùng. Dư luận yêu cầu điều tra. Quyết định đầu tiên của bạn?',
      choices: REGULATOR_ROUNDS[0].choices,
    },
    {
      roundNumber: 1,
      scenario: 'Startup công nghệ Việt Nam cần vốn để cạnh tranh với BigTech nước ngoài. Họ đề nghị ưu đãi thuế. Bạn quyết định?',
      choices: [
        {
          id: 'rg1_alt_a',
          title: 'Ưu đãi thuế toàn diện',
          description: 'Miễn thuế 5 năm cho startup công nghệ Việt',
          effects: { innovation: 25, publicWelfare: 15, fairness: -10, revenue: -15 },
          riskLevel: 'medium',
          consequence: 'Thúc đẩy đổi mới nhưng mất thu ngân sách',
          tags: ['innovation', 'balanced'],
        },
        {
          id: 'rg1_alt_b',
          title: 'Ưu đãi có điều kiện',
          description: 'Ưu đãi nếu cam kết tạo việc làm và R&D',
          effects: { innovation: 20, publicWelfare: 20, fairness: 15, revenue: -8 },
          riskLevel: 'low',
          consequence: 'Cân bằng phát triển và công bằng',
          tags: ['balanced', 'ethical'],
        },
        {
          id: 'rg1_alt_c',
          title: 'Từ chối ưu đãi',
          description: 'Tất cả doanh nghiệp phải tuân thủ luật như nhau',
          effects: { fairness: 20, revenue: 10, innovation: -15, publicWelfare: -10 },
          riskLevel: 'medium',
          consequence: 'Công bằng nhưng startup khó cạnh tranh',
          tags: ['ethical', 'defensive'],
        },
        {
          id: 'rg1_alt_d',
          title: 'Quỹ hỗ trợ startup',
          description: 'Tạo quỹ đầu tư nhà nước cho công nghệ',
          effects: { innovation: 30, publicWelfare: 20, fairness: 10, revenue: -10 },
          riskLevel: 'low',
          consequence: 'Hỗ trợ trực tiếp, hiệu quả cao',
          tags: ['innovation', 'ethical'],
        },
      ],
    },
  ],
  2: [
    {
      roundNumber: 2,
      scenario: 'Nền tảng thương mại điện tử bị tố ép giá sellers nhỏ. Cần điều tra? Hay đợi thêm bằng chứng?',
      choices: REGULATOR_ROUNDS[1].choices,
    },
    {
      roundNumber: 2,
      scenario: 'Công nghệ deepfake đang lan tràn, gây hoang mang dư luận. Quốc hội yêu cầu quy định gấp. Đề xuất của bạn?',
      choices: [
        {
          id: 'rg2_alt_a',
          title: 'Cấm hoàn toàn deepfake',
          description: 'Luật cấm tạo và phát tán nội dung deepfake',
          effects: { publicWelfare: 25, fairness: 15, innovation: -20, userTrust: 10 },
          riskLevel: 'high',
          consequence: 'Bảo vệ người dùng nhưng hạn chế sáng tạo',
          tags: ['ethical', 'defensive'],
        },
        {
          id: 'rg2_alt_b',
          title: 'Quy định minh bạch',
          description: 'Bắt buộc ghi rõ nội dung AI-generated',
          effects: { fairness: 25, publicWelfare: 20, innovation: 10, userTrust: 15 },
          riskLevel: 'low',
          consequence: 'Cân bằng đổi mới và an toàn',
          tags: ['balanced', 'ethical'],
        },
        {
          id: 'rg2_alt_c',
          title: 'Chỉ cấm deepfake có hại',
          description: 'Chỉ xử phạt khi dùng để lừa đảo, bôi nhọ',
          effects: { fairness: 20, innovation: 15, publicWelfare: 15, userTrust: 10 },
          riskLevel: 'medium',
          consequence: 'Linh hoạt nhưng khó thực thi',
          tags: ['balanced'],
        },
        {
          id: 'rg2_alt_d',
          title: 'Giáo dục media literacy',
          description: 'Đầu tư dạy người dùng nhận biết fake content',
          effects: { publicWelfare: 30, innovation: 15, fairness: 10, userTrust: 20 },
          riskLevel: 'low',
          consequence: 'Giải pháp dài hạn, nâng cao nhận thức',
          tags: ['ethical', 'innovation'],
        },
      ],
    },
  ],
  3: [
    {
      roundNumber: 3,
      scenario: 'Nền tảng lớn bị cáo buộc vi phạm quyền riêng tư. Bạn có bằng chứng đủ để xử phạt nhưng họ đe dọa sẽ rút khỏi thị trường. Quyết định?',
      choices: REGULATOR_ROUNDS[2].choices,
    },
    {
      roundNumber: 3,
      scenario: 'Một tập đoàn công nghệ nước ngoài muốn thâu tóm startup tiềm năng của Việt Nam. Điều này có thể ảnh hưởng đến chủ quyền dữ liệu quốc gia. Bạn xử lý thế nào?',
      choices: [
        {
          id: 'rg3_alt_a',
          title: 'Cấm thương vụ',
          description: 'Bảo vệ chủ quyền công nghệ quốc gia',
          effects: { fairness: 20, publicWelfare: 15, innovation: -10, revenue: -15 },
          riskLevel: 'high',
          consequence: 'Bảo vệ lợi ích quốc gia nhưng hạn chế vốn đầu tư',
          tags: ['ethical', 'defensive'],
        },
        {
          id: 'rg3_alt_b',
          title: 'Cho phép với điều kiện',
          description: 'Yêu cầu giữ dữ liệu tại Việt Nam và chuyển giao công nghệ',
          effects: { fairness: 10, innovation: 15, publicWelfare: 10, revenue: 5 },
          riskLevel: 'medium',
          consequence: 'Cân bằng giữa đầu tư nước ngoài và chủ quyền',
          tags: ['balanced'],
        },
        {
          id: 'rg3_alt_c',
          title: 'Cho phép tự do',
          description: 'Không can thiệp vào quyết định kinh doanh',
          effects: { innovation: 20, revenue: 15, fairness: -15, publicWelfare: -20 },
          riskLevel: 'high',
          consequence: 'Thu hút vốn nhưng mất kiểm soát công nghệ',
          tags: ['aggressive'],
        },
        {
          id: 'rg3_alt_d',
          title: 'Hỗ trợ tìm nhà đầu tư trong nước',
          description: 'Kết nối startup với quỹ đầu tư Việt Nam',
          effects: { publicWelfare: 25, fairness: 15, innovation: 10, revenue: 5 },
          riskLevel: 'low',
          consequence: 'Phát triển hệ sinh thái nội địa bền vững',
          tags: ['ethical', 'innovation'],
        },
      ],
    },
  ],
  4: [
    {
      roundNumber: 4,
      scenario: 'Nền tảng AI mới có khả năng tạo nội dung tự động, đe dọa ngành báo chí và sáng tạo nội dung. Bảo vệ người lao động hay thúc đẩy đổi mới?',
      choices: REGULATOR_ROUNDS[3].choices,
    },
    {
      roundNumber: 4,
      scenario: 'Gig economy bùng nổ: Hàng triệu người làm tự do qua app. Nhưng họ không có bảo hiểm, nghỉ phép. Quy định lại như thế nào?',
      choices: [
        {
          id: 'rg4_alt_a',
          title: 'Bắt buộc nền tảng cung cấp quyền lợi',
          description: 'Gig workers được hưởng bảo hiểm, nghỉ phép',
          effects: { publicWelfare: 35, fairness: 30, innovation: -10, revenue: -15 },
          riskLevel: 'medium',
          consequence: 'Bảo vệ lao động nhưng tăng chi phí nền tảng',
          tags: ['ethical'],
        },
        {
          id: 'rg4_alt_b',
          title: 'Hình thức lao động mới',
          description: 'Tạo khung pháp lý riêng cho gig workers',
          effects: { fairness: 25, publicWelfare: 25, innovation: 15, revenue: -5 },
          riskLevel: 'low',
          consequence: 'Linh hoạt, phù hợp xu hướng',
          tags: ['balanced', 'innovation'],
        },
        {
          id: 'rg4_alt_c',
          title: 'Quỹ bảo hiểm tự nguyện',
          description: 'Cho phép workers tự đóng bảo hiểm riêng',
          effects: { publicWelfare: 15, innovation: 15, fairness: 10, revenue: 5 },
          riskLevel: 'medium',
          consequence: 'Tự do lựa chọn nhưng bảo vệ yếu',
          tags: ['balanced'],
        },
        {
          id: 'rg4_alt_d',
          title: 'Giữ nguyên - Tự do thị trường',
          description: 'Không can thiệp, để thị trường tự điều chỉnh',
          effects: { innovation: 20, revenue: 10, publicWelfare: -20, fairness: -15 },
          riskLevel: 'high',
          consequence: 'Thúc đẩy kinh tế nhưng bất công xã hội',
          tags: ['aggressive'],
        },
      ],
    },
  ],
  5: [
    {
      roundNumber: 5,
      scenario: 'Nhiệm kỳ của bạn sắp kết thúc. Bạn có cơ hội ban hành luật về AI tổng quát - định hình tương lai số hóa quốc gia. Di sản của bạn?',
      choices: REGULATOR_ROUNDS[4].choices,
    },
    {
      roundNumber: 5,
      scenario: 'Việt Nam có cơ hội trở thành hub công nghệ ASEAN. Nhưng cần quyết định lớn: Mở cửa hoàn toàn hay bảo hộ có chọn lọc? Quyết sách cuối cùng?',
      choices: [
        {
          id: 'rg5_alt_a',
          title: 'Free Trade + Open Innovation',
          description: 'Mở cửa hoàn toàn, thu hút BigTech toàn cầu',
          effects: { innovation: 40, revenue: 30, fairness: -15, publicWelfare: -10 },
          riskLevel: 'high',
          consequence: 'Tăng trưởng nhanh nhưng startup nội khó cạnh tranh',
          tags: ['aggressive', 'innovation'],
        },
        {
          id: 'rg5_alt_b',
          title: 'Smart Protectionism',
          description: 'Bảo vệ startup nội địa, yêu cầu transfer công nghệ',
          effects: { fairness: 35, publicWelfare: 30, innovation: 20, revenue: 15 },
          riskLevel: 'low',
          consequence: 'Phát triển bền vững, tự chủ công nghệ',
          tags: ['ethical', 'balanced'],
        },
        {
          id: 'rg5_alt_c',
          title: 'Digital Sovereignty First',
          description: 'Ưu tiên chủ quyền số, kiểm soát dữ liệu quốc gia',
          effects: { fairness: 30, publicWelfare: 35, innovation: -10, revenue: 10 },
          riskLevel: 'medium',
          consequence: 'An ninh quốc gia nhưng hạn chế hội nhập',
          tags: ['ethical', 'defensive'],
        },
        {
          id: 'rg5_alt_d',
          title: 'ASEAN Digital Alliance',
          description: 'Liên minh công nghệ khu vực, cùng phát triển',
          effects: { fairness: 30, innovation: 30, publicWelfare: 30, revenue: 20 },
          riskLevel: 'low',
          consequence: 'Hợp tác đa phương, cân bằng lợi ích',
          tags: ['balanced', 'innovation'],
        },
      ],
    },
  ],
};

// Get round with variations for more diversity
export const getRoundWithVariation = (role: string, roundNumber: number): Round => {
  const baseRounds = ROUNDS_BY_ROLE[role] || [];
  const baseRound = baseRounds[roundNumber - 1];
  
  // Check if variations exist for this round
  let variations: Round[] = [];
  if (role === 'smallbiz' && SMALLBIZ_ROUND_VARIATIONS[roundNumber]) {
    variations = SMALLBIZ_ROUND_VARIATIONS[roundNumber];
  } else if (role === 'platform' && PLATFORM_ROUND_VARIATIONS[roundNumber]) {
    variations = PLATFORM_ROUND_VARIATIONS[roundNumber];
  } else if (role === 'regulator' && REGULATOR_ROUND_VARIATIONS[roundNumber]) {
    variations = REGULATOR_ROUND_VARIATIONS[roundNumber];
  }
  
  // 50% chance to use variation if available
  if (variations.length > 0 && Math.random() > 0.5) {
    const variation = variations[Math.floor(Math.random() * variations.length)];
    return {
      ...variation,
      choices: shuffleArray(variation.choices),
    };
  }
  
  return {
    ...baseRound,
    choices: shuffleArray(baseRound.choices),
  };
};
